# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: saad489254@gmial.com
author_name: SaadAbdullah72
cloud_provider: netlify
contract_name: trust_vault
deployment_language: python
preset_name: production
project_name: TrustVault

